### ISSUE TITLE
createHttpClient is undefined

### ISSUE THREAD

**Issue by pihomeserver** [gobwas/influent#13]
Hello,

I installed influent via npm and can not use it in my nodes project, the createHttpClient method as described in the Readme is not defined (that correct based on the source code in the dist folder ...). Here is a console.log of influent object :

``` javascript
import config from '../../config/environment';

var influent = require('influent');
var influentClient = influent.createClient(config.influxServer);

console.log(influent)
```

The result is

```
{ Client:
   { [Function: Client]
     DEFAULTS: { precision: null, epoch: null },
     extend: [Function] },
  HttpClient:
   { [Function]
     DEFAULTS:
      { precision: null,
        epoch: null,
        max_batch: 5000,
        health_check_duration: 1800000 },
     extend: [Function] },
  Serializer: { [Function: Serializer] extend: [Function] },
  LineSerializer: { [Function] extend: [Function] },
  Value: [Function: Value],
  Measurement: [Function: Measurement],
  Host: [Function: Host],
  type:
   { getInfluxTypeOf: [Function],
     STRING: 0,
     FLOAT64: 1,
     INT64: 2,
     BOOLEAN: 3,
     TYPE: [ 0, 1, 2, 3 ] },
  createClient: [Function] }
```

Any idea how to perform a basic query ?

**Comment by gobwas** [comment]
Hi @pihomeserver!

Method `createHttpClient` is not released yet as stable – as you can see, there is `0.4.2` version in npm (e.g. run `npm view influent`), and this method exists now only in release candidate version `0.5.0-rc.4`. You could install it via `npm install influent@next` or wait few days till I finish some other things and will release it as stable =)

**Comment by pihomeserver** [comment]
Wahoo really fast answer. I am still in dev too so i will use the "beta" program ;-)

**Comment by gobwas** [comment]
@pihomeserver :beers:

**Comment by gobwas** [comment]
@pihomeserver hi! Have you had a chance to try `influent@0.5.0-rc.7` yet? I will publish it as release soon, If every body is OK with that changes I've made.

**Comment by pihomeserver** [comment]
@gobwas hi. I installed it on a clone of my project and it works. But i only use the query promise. Not sure it's enough useful for you

**Comment by gobwas** [comment]
@pihomeserver thanks, any way!
