### ISSUE TITLE
provide more info on unknown status codes

### ISSUE THREAD

**Issue by hans-d** [gobwas/influent#14]
https://github.com/gobwas/influent/blob/8bc8d8586d1c91abc9410eae904a35452598116c/lib/client/http.js#L229

Would be nice to get some more info than just a `Error: InfluxDB unknown status code: 500`, such as http body and headers. This could be done in an additional field.

A bit further down the road, the various 500 codes could be detected and reported specifically within this section. For the short term this is not directly needed (but the additional info is)

**Comment by gobwas** [comment]
Hi @hans-d!
Im not sure yet that info about why something went really wrong on the database server should be fetched via database driver. I mean, may be it is better to search this info in the database logs?

At this moment I think it could be good idea to use some abstract logger object, that could be injected in `influent` somehow. And then influent will log debug info via this object. Hm?

**Comment by hans-d** [comment]
Hi. This info should be fetched. Some 500 errors are fatal, some are not. You capture other errors, like invalid syntax, so why should other error info should not be available.
Eg I've got some 500 errors indicating that the WAL needs some room to breathe and write should be temp slowed down / pauzed. That's not a fatal error or something went really wrong, but something that can be recovered.

**Comment by gobwas** [comment]
Yeah, this thing `5xx: The system is overloaded or significantly impaired.` from [docs](https://influxdb.com/docs/v0.9/guides/writing_data.html) looks like that it could be significant.. Which source you analyzed to get info about WAL? Body?

**Comment by hans-d** [comment]
Fetching the info via the database logs is for these recoverable errors is a workaround.
If the info should be logged is another thing, I just want the info attached to the generated error so I can perform some logic on it to see if and how it can be recovered.

**Comment by hans-d** [comment]
I expect that the body of a 500 contains some basic error message. Thats enough to work with. Any specifics, eg why it occurs this frequently, should indeed be done via the db logs as they provide more context. Not expecting to fix the underlying cause or from the app side, but at least for a write I can do a retry later on.

**Comment by gobwas** [comment]
Done in `0.5.2`
