### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by dandv** [gobwas/influent#19]
At [one point in time](https://github.com/node-influx/node-influx/pull/92#issuecomment-160669397) this library was apparently more actively maintained than node-influx.

**Comment by gobwas** [comment]
Hey @dandv this library is just works, I think =)
Do you need some new features?

**Comment by beckettsean** [comment]
@gobwas there have been significant changes to InfluxDB since 0.9. I doubt this library is still compatible with InfluxDB 1.0

http://docs.influxdata.com/influxdb/v1.0/administration/1_vs_previous/

As there are other Node libraries with very active maintainers, we've chosen to stop listing this on the API Libraries page for InfluxDB.

**Comment by gobwas** [comment]
@beckettsean hi ) which differences I need to cover in current implementation? I quick listed your link, and did not found any changes to http/udp api or sending query string to influxd.

**Comment by eliperelman** [comment]
@bekettsean I also had node-influx removed from the API clients page because it hasn't properly supported InfluxDB since 0.9 when integer entries were changed in the line protocol.

**Comment by dandv** [comment]
@eliperelman: that would mean there are no [JavaScript clients](https://docs.influxdata.com/influxdb/v1.0/tools/api_client_libraries/#javascript-node-js) left.

FWIW, [writing integers](https://github.com/node-influx/node-influx/issues/190#issuecomment-252157746) is [in the upcoming v5.0](https://github.com/node-influx/node-influx/blob/5.0.0/src/index.ts#L540) of node-influx.

**Comment by connor4312** [comment]
Saw this referenced in an issue on `node-influx`. We now support Influx 1.0 (and writing integers!) in `5.0.0-alpha.1` which was just published. There are still many features that Influx has added that I want to support in future minor versions, but `influx` should now have baseline compatibility with 1.0 (cc @eliperelman).

If you'd like to try it out you can install it via

```
npm install --save influx@next
```

You can also see the non-comprehensive ~~changelog~~ change overview here: https://node-influx.github.io/manual/changelog.html#2016-10-15-5-0-0-alpha-1
