### ISSUE TITLE
Switch client check to use ping instead of databases query

### ISSUE THREAD

**Issue by eliperelman** [gobwas/influent#5]
When initializing influent, it makes a connection to the configured database for a health check by running the query `show databases`, but this query requires the connected user to have admin privileges. In my use case, I would like the DB user that writes to the DB to not have admin privileges. Instead, switch the health check to hit the `/ping` endpoint, which should be sufficient for a health check, but doesn't require elevated rights.

**Comment by gobwas** [comment]
@eliperelman yeah, thats right. Coming soon :sunglasses:

**Comment by gobwas** [comment]
Hi again )
Version `0.4.0-rc.0` is out now. Could you review/test these changes?
Could be installed as:

``` shell
npm install influent@next
```

**Comment by eliperelman** [comment]
@gobwas works great! :shipit:

**Comment by gobwas** [comment]
@eliperelman just released as `0.4.0` :sunglasses:

**Comment by eliperelman** [comment]
@gobwas you sir are awesome! Thanks!

**Comment by gobwas** [comment]
@eliperelman :joy: :beers:
