### ISSUE TITLE
Client ping check not functional on Influxdb 0.9.4.2

### ISSUE THREAD

**Issue by johnfox** [gobwas/influent#6]
I'm using the influent with influxdb 0.9.4.2 and got this issue:
When the request is made to the /ping endpoint the influxdb does not return any headers causing the influent to fail in following:

``` javascript
info.setVersion(resp.headers["x-influxdb-version"]);
info.setDate(new Date(resp.headers["date"]));
```

as the resp.headers is undef.
this is my resp content:

```
Object {body: "", statusCode: 204}
```

In my configuration I have read only user that is accessing the DB.

**Comment by gobwas** [comment]
Could you run this on InfluxDB host machine:

``` shell
curl -v localhost:8086/ping
```

?

**Comment by gobwas** [comment]
The [spec](https://influxdb.com/docs/v0.9/concepts/api.html) seems to does not change..

**Comment by johnfox** [comment]
Without the ping endpoint :

```
curl -v localhost:8086
* About to connect() to localhost port 8086 (#0)
*   Trying 127.0.0.1... connected
> GET / HTTP/1.1
> User-Agent: curl/7.22.0 (x86_64-pc-linux-gnu) libcurl/7.22.0 OpenSSL/1.0.1 zlib/1.2.3.4 libidn/1.23 librtmp/2.3
> Host: localhost:8086
> Accept: */*
> 
< HTTP/1.1 404 Not Found
< Content-Type: text/plain; charset=utf-8
< X-Content-Type-Options: nosniff
< Date: Mon, 12 Oct 2015 11:16:51 GMT
< Content-Length: 19
< 
404 page not found
* Connection #0 to host localhost left intact
* Closing connection #0
```

With /ping endpoint:

```
curl -v localhost:8086/ping
* About to connect() to localhost port 8086 (#0)
*   Trying 127.0.0.1... connected
> GET /ping HTTP/1.1
> User-Agent: curl/7.22.0 (x86_64-pc-linux-gnu) libcurl/7.22.0 OpenSSL/1.0.1 zlib/1.2.3.4 libidn/1.23 librtmp/2.3
> Host: localhost:8086
> Accept: */*
> 
< HTTP/1.1 204 No Content
< Request-Id: c5ea2e24-70d2-11e5-a256-000000000000
< X-Influxdb-Version: 0.9.4.2
< Date: Mon, 12 Oct 2015 11:17:07 GMT
< 
* Connection #0 to host localhost left intact
* Closing connection #0
```

It seems like the header is there when CURLing.
I forgot to mention I'm using the influent in the browser - Chrome (45.0.2454.101 (64-bit))

**Comment by gobwas** [comment]
Yeah, that was I thinking of. The browser version still need to be better tested. Will try to figure out the bug source. Thanks!

**Comment by johnfox** [comment]
I plan to use Influent in browser so I can post you anything I will come across. Although I don't plan to use it for writing values. Cheers!

**Comment by gobwas** [comment]
So it seems the problem with InfluxDB CORS response headers. I will think a little bit, how to solve this right now, but systematically, I hope on this [PR](https://github.com/influxdb/influxdb/pull/4411). =)

**Comment by gobwas** [comment]
Fixed out this behaviour in `0.4.2` - now the `Info` object has optional `version` and `date`. Not so strict, as it was earlier. Please ping me to close this issue when your will try it.

**Comment by johnfox** [comment]
It works :) great job sir.

**Comment by gobwas** [comment]
:beers: :sunglasses:
