### ISSUE TITLE
Authentication problem

### ISSUE THREAD

**Issue by johnfox** [gobwas/influent#7]
When querying I have encountered following issue. The auth in the "query" method of the HttpClient class:

``` javascript
.request(host.toString() + "/query", {
                            method: "GET",
                            auth: {
                                username: options.username,
                                password: options.password
                            },
```

is either ignored or not recognised by the server. Response from server:

```
GET http://localhost:8086/query?db=my_db&q=<...SNIP...> 401 (Unauthorized)
```

I have changed the source to incorporate the credentials to the query and it is working as expected:

``` javascript
.request(host.toString() + "/query", {
                            method: "GET",
                            // auth: {
                            //     username: options.username,
                            //     password: options.password
                            // },
                            query: _.extend(queryObj, {
                                db: options.database,
                                u: options.username,
                                p: options.password,
                                q:  query
                            })
                        })
```

I'm using Influxdb version 0.9.4.2

**Comment by johnfox** [comment]
Forgot to mention I'm using Influent from browser - Chrome (45.0.2454.101 (64-bit))

**Comment by gobwas** [comment]
Catch out `0.4.2` version with fixes of this bug. Please, ping me, that if works – I will close this ticket then =)

**Comment by gobwas** [comment]
Catch out `0.4.2` version with fixes of this bug. Please, ping me, that if works – I will close this ticket then =)

**Comment by johnfox** [comment]
Hey, I do confirm it works :) great!

**Comment by gobwas** [comment]
:beers:
